In [5]:
import numpy as np

In [11]:
a = np.array([[1,6],
             [2,8],
             [3,11],
             [3,10],
             [1,7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [12]:
mean_a=a.mean(axis=0)
mean_a

array([2. , 8.4])

In [14]:
a_centered=a-mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [33]:
a_c_0 = a_centered.transpose()[0:1] 
a_c_1 = np.transpose(a_centered.transpose()[1:])
a_centered_sp=np.dot(a_c_0,a_c_1)
a_centered_sp

array([[8.]])

In [34]:
a_centered_sp/4

array([[2.]])

In [36]:
np.cov(np.transpose(a))[0,1]

2.0